kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
        # Send severity=Critical alerts to slack.
          matchers:
            - severity = Critical
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: 283500@student.pwr.edu.pl
        send_resolved: false
        from: festus.udomoh@gmail.com
        smarthost: smtp.gmail.com:587
        require_tls: false
        auth_username: festus.udomoh@gmail.com
        auth_identity: festus.udomoh@gmail.com
        auth_password: Testing123
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/<token>
        channel: '#auto-deploy-nodejs-app'
        text: <https://github.com/WUST-Projects/ITAPP_THU0730_FleetmanVehicleReliabilityandMTTDSystem/blob/main/prometheus/alert-manager/runbook.md|Runbook URL>