---
# Source: spire/charts/spiffe-oidc-discovery-provider/templates/pre-delete-hook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: spire-server-spiffe-oidc-discovery-provider-pre-delete
  namespace: spire-server
  labels:
    helm.sh/chart: spiffe-oidc-discovery-provider-0.1.0
    app.kubernetes.io/name: spiffe-oidc-discovery-provider
    app.kubernetes.io/instance: spire-server
    app.kubernetes.io/version: "1.12.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
spec:
  template:
    metadata:
      name: spire-server-spiffe-oidc-discovery-provider-pre-delete
    spec:
      restartPolicy: Never
      serviceAccountName: spire-server-spiffe-oidc-discovery-provider-pre-delete
      securityContext:
        {}
      containers:
      - name: pre-delete-job
        securityContext:
          {}
        image: "docker.io/rancher/kubectl:v1.27.0"
        args:
          - delete
          - -n
          - spire-server
          - deployment
          - spire-server-spiffe-oidc-discovery-provider
          - --wait
---
# Source: spire/charts/spire-server/templates/post-install-hook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: spire-server-post-install
  namespace: spire-server
  labels:
    helm.sh/chart: spire-server-0.1.0
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: spire-server
    app.kubernetes.io/version: "1.12.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
spec:
  template:
    metadata:
      name: spire-server-post-install
    spec:
      restartPolicy: Never
      serviceAccountName: spire-server-post-install
      securityContext:
        {}
      containers:
      - name: post-install-job
        securityContext:
          {}
        image: "docker.io/rancher/kubectl:v1.27.0"
        args:
          - patch
          - validatingwebhookconfiguration
          - spire-server-spire-controller-manager-webhook
          - --type=strategic
          - -p
          - |
            {
              "webhooks":[
                {
                  "name":"vclusterspiffeid.kb.io",
                  "failurePolicy":"Fail"
                },
                {
                  "name":"vclusterfederatedtrustdomain.kb.io",
                  "failurePolicy":"Fail"
                }
              ]
            }
---
# Source: spire/charts/spire-server/templates/post-upgrade-hook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: spire-server-post-upgrade
  namespace: spire-server
  labels:
    helm.sh/chart: spire-server-0.1.0
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: spire-server
    app.kubernetes.io/version: "1.12.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
spec:
  template:
    metadata:
      name: spire-server-post-upgrade
    spec:
      restartPolicy: Never
      serviceAccountName: spire-server-post-upgrade
      securityContext:
        {}
      containers:
      - name: post-upgrade-job
        securityContext:
          {}
        image: "docker.io/rancher/kubectl:v1.27.0"
        args:
          - patch
          - validatingwebhookconfiguration
          - spire-server-spire-controller-manager-webhook
          - --type=strategic
          - -p
          - |
            {
              "webhooks":[
                {
                  "name":"vclusterspiffeid.kb.io",
                  "failurePolicy":"Fail"
                },
                {
                  "name":"vclusterfederatedtrustdomain.kb.io",
                  "failurePolicy":"Fail"
                }
              ]
            }
---
# Source: spire/charts/spire-server/templates/pre-upgrade-hook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: spire-server-pre-upgrade
  namespace: spire-server
  labels:
    helm.sh/chart: spire-server-0.1.0
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: spire-server
    app.kubernetes.io/version: "1.12.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
spec:
  template:
    metadata:
      name: spire-server-pre-upgrade
    spec:
      restartPolicy: Never
      serviceAccountName: spire-server-pre-upgrade
      securityContext:
        {}
      containers:
      - name: post-install-job
        securityContext:
          {}
        image: "docker.io/rancher/kubectl:v1.27.0"
        args:
          - patch
          - validatingwebhookconfiguration
          - spire-server-spire-controller-manager-webhook
          - --type=strategic
          - -p
          - |
            {
              "webhooks":[
                {
                  "name":"vclusterspiffeid.kb.io",
                  "failurePolicy":"Ignore"
                },
                {
                  "name":"vclusterfederatedtrustdomain.kb.io",
                  "failurePolicy":"Ignore"
                }
              ]
            }
