apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/applications

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    patch: |-
      - op: replace
        path: /metadata/name
        value: kiali
      - op: replace
        path: /spec/source/path
        value: argocd/overlays/tools/kiali
      - op: replace
        path: /spec/destination/namespace
        value: istio-system
