---
apiVersion: v1
data:
  github_app_id: APP_ID
  github_app_installation_id: INSTALLATION_ID
  github_app_private_key: PRIVATE_KEY
kind: Secret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-system
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: actions-runner-system
spec:
  dnsNames:
  - webhook-service.actions-runner-system.svc
  - webhook-service.actions-runner-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
