name: Deploy infra for eu-central-1

on:
  workflow_dispatch:
    
jobs:
  infra-setup:
    runs-on: [self-hosted, eu-central-1]
    name: Setup infra for eu-central-1

    steps:
      - name: Install spire
        working-directory: ./spire
        run: |
          /bin/bash setup.sh
