name: Deploy infra for eu-west-1

on:
  workflow_dispatch:
    
jobs:
  infra-setup:
    runs-on: [eu-west-1]
    name: Setup infra for eu-west-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
          rm awscliv2.zip

      # Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Change to your required version

      - name: Configuring kubectl for eu-west-1
        working-directory: ./terraform/env/eu-west-1
        run: |
          terraform init
          terraform refresh
          aws eks --region $(terraform output -json | jq -r ".[].value.region") update-kubeconfig \
          --name $(terraform output -json | jq -r ".[].value.cluster_name")
          rm -rf .terraform
          rm -f .terraform.lock*

      - name: Installing argocd
        working-directory: argocd/bootstrap
        run: |
          sed -i "s|APP_ID|$(echo "${{ secrets.APP_ID }}")|" app-secret.yaml
          sed -i "s|INSTALLATION_ID|$(echo "${{ secrets.INSTALLATION_ID }}")|" app-secret.yaml
          sed -i "s|PRIVATE_KEY|$(echo "${{ secrets.APP_PRIVATE_KEY }}")|" app-secret.yaml
          kubectl apply -f app-secret.yaml

          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          helm upgrade --install thesis-gitops argo/argo-cd --version 8.1.2 \
              --namespace argocd \
              --create-namespace 
